services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 4000:4000

  frontend:
    build: ./
    volumes:
      - ./:/app
      - /node_modules
    ports:
      # SWS in the Dockerfile defaults to port 80.
      - 5173:80
